### ISSUE TITLE
Colours don't show on wolf collars.

### ISSUE THREAD

**Issue by AmyMialee** [Eltrut-Co/Flamboyant-Refabricated#5] opened 2021-05-26 00:08 UTC
It allows you to dye them but they become invisible. 
Image using pale green dye.
![image](https://user-images.githubusercontent.com/10999535/119583618-e34f6800-bdbe-11eb-8cd5-07354f042255.png)

**Comment by Steven-Baez** [comment] 2021-11-01 23:40
duplicate of #7

**Closed as completed by Steven-Baez** 2021-11-01 23:40 UTC
Labels: bug, enhancement
